static class ServiceTypeOptions
{
    internal const int SERVICE_TYPE_ADAPTER = 0x00000004;
    internal const int SERVICE_TYPE_FILE_SYSTEM_DRIVER = 0x00000002;
    internal const int SERVICE_TYPE_INTERACTIVE_PROCESS = 0x00000100;
    internal const int SERVICE_TYPE_KERNEL_DRIVER = 0x00000001;
    internal const int SERVICE_TYPE_RECOGNIZER_DRIVER = 0x00000008;
    internal const int SERVICE_TYPE_WIN32_OWN_PROCESS = 0x00000010;
    internal const int SERVICE_TYPE_WIN32_SHARE_PROCESS = 0x00000020;
    internal const int SERVICE_TYPE_WIN32 =
        SERVICE_TYPE_WIN32_OWN_PROCESS |
        SERVICE_TYPE_WIN32_SHARE_PROCESS;
    internal const int SERVICE_TYPE_DRIVER =
        SERVICE_TYPE_KERNEL_DRIVER |
        SERVICE_TYPE_FILE_SYSTEM_DRIVER |
        SERVICE_TYPE_RECOGNIZER_DRIVER;
    internal const int SERVICE_TYPE_ALL =
        SERVICE_TYPE_WIN32 |
        SERVICE_TYPE_ADAPTER |
        SERVICE_TYPE_DRIVER |
        SERVICE_TYPE_INTERACTIVE_PROCESS;
}