image: Visual Studio 2019 Preview
skip_commits:
  message: /doco|Merge pull request.*/
install:
- cmd: choco install dotnetcore-sdk --pre
build_script:
- cmd: dotnet build src --configuration Release
test:
  categories:
    except:
    - Integration
artifacts:
- path: nugets\*.nupkg